### PR TITLE
EE-1334: updated pyega3 README

### PR DESCRIPTION
**Pull request by malloryfreeberg**
## Summary of changes
* Added README.md file
* Updated Requirements and Installation sections
* Updated Troubleshooting section, including instructions for sending HD log file
* General improvements in tone and organisation
* Deleted out-of-date README.txt file

## Missing changes
* Updates for new `clean` subcommand and `delete-temp-files` argument (see #89)

### CODE REVIEW

**Comment by malloryfreeberg** [comment]
@anandmohan777 here I'll summarise the questions from myself and Bela:
* What command should Windows users use to install pyega3? Is it different from the examples already listed for pip3 or conda or GH?
* Is there a use for `README.txt` or can it be deleted in this PR?
* Do you suggest we list all the python modules in the "Requirements" section of the README? Or is it enough that they are in `requirements.txt`?
* Do you suggest we provide instructions in the README for installing individual python modules? Or is it enough that they are automatically installed via pip, conda, or setup.py (for GH installations)?

Thanks!

**Comment by bela-juhasz** [comment]
>     * Is there a use for `README.txt` or can it be deleted in this PR?

Maybe the README.txt is the file which is used by PyPi (the website behind the `pip install pyega3` command): https://pypi.org/project/pyega3/

We should read the documentation of the PyPi website: maybe they parse README.**md** files, too, if no README.**txt** is found.

I haven't seen the README.txt being used on the https://bioconda.github.io/recipes/pyega3/README.html page, though.

**Comment by bela-juhasz** [comment]
> > ```
> > * Is there a use for `README.txt` or can it be deleted in this PR?
> > ```
> 
> Maybe the README.txt is the file which is used by PyPi (the website behind the `pip install pyega3` command): https://pypi.org/project/pyega3/
> 
> We should read the documentation of the PyPi website: maybe they parse README.**md** files, too, if no README.**txt** is found.

PyPi [does support README.md](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#creating-a-readme-file), so I think we can delete the README.txt.

**Comment by malloryfreeberg** [comment]
> > > ```
> > > * Is there a use for `README.txt` or can it be deleted in this PR?
> > > ```
> > 
> > 
> > Maybe the README.txt is the file which is used by PyPi (the website behind the `pip install pyega3` command): https://pypi.org/project/pyega3/
> > We should read the documentation of the PyPi website: maybe they parse README.**md** files, too, if no README.**txt** is found.
> 
> PyPi [does support README.md](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#creating-a-readme-file), so I think we can delete the README.txt.

Great! I'll remove README.txt then.

**Comment by anandmohan777** [comment]
> @anandmohan777 here I'll summarise the questions from myself and Bela:
> 
> * What command should Windows users use to install pyega3? Is it different from the examples already listed for pip3 or conda or GH?
> * Is there a use for `README.txt` or can it be deleted in this PR?
> * Do you suggest we list all the python modules in the "Requirements" section of the README? Or is it enough that they are in `requirements.txt`?
> * Do you suggest we provide instructions in the README for installing individual python modules? Or is it enough that they are automatically installed via pip, conda, or setup.py (for GH installations)?
> 
> Thanks!

Hi @malloryfreeberg   the PR looks great. 👏🏻👏🏻
Below are my suggestions:
1. For windows, installation command is same as others no need to write separately
2. README.txt can be deleted as we have now new README.md 
3. I think it is not required to list the modules. If somebody wants to install it manually they can try following command which will install all the dependencies `pip install -r requirements.txt`
4. I think it is not required to list the modules in README. "pip3 install pyega3" commands itself installs all the dependencies automatically. And for GH installation this can be used `pip install -r requirements.txt`

**Pull request merged**
